master
urfu-2017/webdev-task-4 pull request #30
Opened 2018-03-29 12:40 UTC by WBDiamond

2018-03-29 12:41 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-29 12:44 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-04-02 16:47 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-04-02 16:53 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-04-03 11:26 UTC, noveogroup-amorgunov requested changes

2018-04-03 11:26 UTC, noveogroup-amorgunov commented on images/multiply.svg
> +<?xml version="1.0" encoding="iso-8859-1"?>
давай файл сожмем через svgo

2018-04-03 11:26 UTC, noveogroup-amorgunov commented on .idea/codeStyleSettings.xml
> +</project>
![giphy](https://user-images.githubusercontent.com/21186268/38240976-86b91348-3720-11e8-855f-62f876593704.gif)

2018-04-03 11:26 UTC, noveogroup-amorgunov commented on index.css
> +    margin: 0;
Поставить по умолчанию шрифт 'Helvetica Neue', Helvetica, Arial, sans-serif;

2018-04-03 11:26 UTC, noveogroup-amorgunov commented on index.css
> +.navigation__element__first
не по бэм-у, не может быть два одновременно элемента, нужно использовать модификатор

2018-04-03 11:26 UTC, noveogroup-amorgunov commented on index.css
> +.order-box__form-line__input
не по бэм-у

2018-04-03 11:26 UTC, noveogroup-amorgunov commented on index.css
> +.order-box__form-line__title
не по бэм-у

2018-04-03 11:26 UTC, noveogroup-amorgunov commented on index.css
> +    main
не по бэм-у, нужно использовать классы вместо тегов

2018-04-03 11:26 UTC, noveogroup-amorgunov commented on index.js
> +        document.querySelector('.header-content__form').classList.add('display');
классы hidden display это не по бэм-у, нужно устанавливать класс с модификатором например для header-content__header -> header-content__header_hidden

2018-04-03 11:26 UTC, noveogroup-amorgunov commented on index.js
> +        let xUp = evt.touches[0].clientX;
почему let а не const?

2018-04-03 11:26 UTC, noveogroup-amorgunov commented on index.js
> +    let input = document.querySelector('.header-content__text-input');
let -> const

2018-04-03 11:26 UTC, noveogroup-amorgunov commented on index.html
> +                        <input type="text" name="count" class="order-box__form-line__input">
могу ввести не число и отрицательное значение (на уровне html все можно решить)

2018-04-03 11:26 UTC, noveogroup-amorgunov commented on index.html
> +                        <select name="Cities" class="order-box__form-line__input">
давай стилизуем select в соответствии с остальными инпутами

2018-04-03 11:26 UTC, noveogroup-amorgunov commented on index.html
> +                        <input type="text" name="email" placeholder="email"
могу ввести не почту, нужно исправить

2018-04-03 11:26 UTC, noveogroup-amorgunov commented on index.html
> +                        <input type="button" name="cancel" value="Сбросить заказ">
изменить на тип reset

2018-04-03 11:26 UTC, noveogroup-amorgunov commented on index.html
> +                        <input type="button" name="order" value="Заказать">
изменить на тип submit

2018-04-03 11:26 UTC, noveogroup-amorgunov commented on index.html
> +                                <span class="souvenir-panel__grade-block__grade">4.0</span>
Сделать рейтинг как в макете

2018-04-03 11:26 UTC, noveogroup-amorgunov commented on index.html
> +                            class="header-content__text-input header-content__element">
В планшетном режиме при нажатии на лупу содержимое хедера становится пустым

2018-04-03 11:26 UTC, noveogroup-amorgunov commented on index.html
> +                            class="header-content__text-input header-content__element">
И закрытие меню свапом не работает

2018-04-03 11:26 UTC, noveogroup-amorgunov commented on index.html
> +                            <a class="navigation__element">Марки из разных стран</a>
добавить аттирибут href что-бы элементы выглядели как ссылки, а не текст

2018-04-03 16:31 UTC, WBDiamond commented on index.css
> +    margin: 0;
А как его ставить без "*"?

2018-04-03 21:08 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-04-03 21:22 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-04-03 21:25 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-04-03 21:30 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-04-03 21:35 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-04-04 07:11 UTC, noveogroup-amorgunov approved these changes

2018-04-04 07:11 UTC, noveogroup-amorgunov commented on index.css
> +}
По идеи если ты body/html задаешь шрифт, и в дочерних нодах его не изменяешь, он и будет использоваться. поэтому html, body { font-family: ... } работало бы норм

2018-04-04 07:11 UTC, noveogroup-amorgunov commented on index.js
> +    document.addEventListener('touchmove', handleTouchMove, false);
Тут не ошибка, но правильней было бы навешивать на  touchend, а я только начинаю свапать и меню уже закрывается

2018-04-04 07:11 UTC, closed without merging