Хомич Павел
urfu-2017/webdev-task-4 pull request #38
Opened 2018-04-05 13:55 UTC by paulkhomich

Я тупо забыл сделать ПР в прошлый раз :О
По датам комитов можно посмотреть :(

2018-04-05 13:55 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-04-06 08:47 UTC, noveogroup-amorgunov requested changes
Посмотрим что можно будет сделать с тегами и итоговой оценкой, но сперва ошибки нужно поправить

2018-04-06 08:47 UTC, noveogroup-amorgunov commented on index.css
> +.footer
footer - подвал, header шапка)
![uh oh oops gif-source](https://user-images.githubusercontent.com/21186268/38409563-63b6c842-3971-11e8-86fd-3d9db4172d2e.gif)

2018-04-06 08:47 UTC, noveogroup-amorgunov commented on index.css
> +.footer_logo
не по бэм-у, logo - элемент, отделять нужно через __

2018-04-06 08:47 UTC, noveogroup-amorgunov commented on index.css
> +.footer_search
тоже самое, не по бэм-у
нужно поправить во всех местах

2018-04-06 08:47 UTC, noveogroup-amorgunov commented on index.css
> +.footer_search > input
тут кроме использования элемента (вместо идентификатора) по бэм-у нельзя использовать теги (только классы), например `.footer__search-input`

2018-04-06 08:47 UTC, noveogroup-amorgunov commented on index.css
> +.navigation > a
тег -> класс
Тоже нужно это везде поправить

2018-04-06 08:47 UTC, noveogroup-amorgunov commented on index.html
> +    <script src="./hammer.min.js"></script>
По задаче нельзя использовать внешние либы, нужно написать свои обработчики на touchstart, touchend

2018-04-06 08:47 UTC, noveogroup-amorgunov commented on index.html
> +            <div class="footer_button">Найти</div>
нужно обернуть интуп и кнопку в форму, вместо дива использовать input type=submit

2018-04-06 08:47 UTC, noveogroup-amorgunov commented on index.html
> +            <a href="/">Морские ракушки</a>
можно использовать href="#" что-бы оставаться на этой же странице при нажатии, удобно при вертске

2018-04-06 08:47 UTC, noveogroup-amorgunov commented on index.html
>  <html lang="ru">
Что то пошло не так
![2018-04-06_14-53-56](https://user-images.githubusercontent.com/21186268/38409928-d586a0fe-3972-11e8-8bd5-a6a5d35b475a.png)

2018-04-06 08:47 UTC, noveogroup-amorgunov commented on index.html
> +                <span>Популярные товары</span>
Зачем тут span?

2018-04-06 08:47 UTC, noveogroup-amorgunov commented on index.html
> +        <div class="order">
Обернуть в форму

2018-04-06 08:47 UTC, noveogroup-amorgunov commented on index.html
> +                <input id="num" type="number">
сделать валидацию чтобы нельзя было вводить числа меньше 1

2018-04-06 08:47 UTC, noveogroup-amorgunov commented on index.html
> +                <button>Заказать</button>
выставить для кнопок нужные типы, для сабмита и ресета формы

2018-04-06 08:47 UTC, noveogroup-amorgunov commented on index.js
> +    const searchTab = document.getElementsByClassName('footer_search')[0];
getElementsByClassName -> querySelector

2018-04-06 08:47 UTC, noveogroup-amorgunov commented on index.js
> +    Hammer(body).on('swipeleft', function () {
сейчас менюшку пустую можно вытащить и на десктопной версии, причем она будет пустая, странное поведение

2018-04-06 08:47 UTC, noveogroup-amorgunov commented on index.js
> +    const body = document.getElementsByTagName('body')[0];
document.body

2018-04-06 08:47 UTC, noveogroup-amorgunov commented on index.js
> +function min720() {
Нужно дать более информативное название или коммент что делает функция. И все ломается при ресайзе, а это плохо, так как можно менять ориентацию

2018-04-06 08:47 UTC, noveogroup-amorgunov commented on index.js
> +    body.style.overflow = 'hidden';
нужно вместо инлайн стилей сделать это по бэм-у - с помощью модификаторов
Поправить нужно везде

2018-04-06 13:58 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-04-06 13:58 UTC, paulkhomich commented on index.html
>  <html lang="ru">
max-width сделал

2018-04-06 14:01 UTC, paulkhomich commented
Да я сам виноват, проспал, так что все нормально
Но у меня вторая сдана полностью до срока - а закрыли с half-accepted, почему так?
И еще третья у нас зависла, там получается hrundel тоже выставит мне half, хотя я все сдал по срокам 😞

2018-04-09 04:13 UTC, noveogroup-amorgunov commented
> Но у меня вторая сдана полностью до срока - а закрыли с half-accepted, почему так?

ЕСли есть проблемы, пиши сразу, оценка автоматически проставляется, и не всегда верно. Вроде поправил

> И еще третья у нас зависла, там получается hrundel тоже выставит мне half, хотя я все сдал по срокам 😞

Тоже гляну, пока времени к сожалению нет

2018-04-09 04:16 UTC, noveogroup-amorgunov approved these changes

2018-04-09 04:16 UTC, noveogroup-amorgunov commented on index.js
> +let x = 0;
лучше глобальную область видимости не засорять и поместить переменную внутрь onload

2018-04-09 04:17 UTC, closed without merging