Андрюшкин Аркадий
urfu-2017/webdev-task-4 pull request #41
Opened 2018-05-11 06:42 UTC by Edheltur

2018-05-11 06:43 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-05-15 06:13 UTC, Savichev-Igor commented
🍪

2018-05-15 06:13 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-05-15 06:17 UTC, savichev-igor commented
🍪

2018-05-15 06:17 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-05-15 20:35 UTC, evgenymarkov requested changes

2018-05-15 20:35 UTC, evgenymarkov commented on index.html
> +    <div class="head__hamburger hamburger">
Кажется гамбургер вылез на десктопе к левому блоку ссылок

2018-05-15 20:35 UTC, evgenymarkov commented on index.html
> +    <a class="list__item">Морские Ракушки</a>
Поставь href заглушки

2018-05-15 20:35 UTC, evgenymarkov commented on index.html
> +
Ощущение будто пустая строка и `</div>` не на своих местах

2018-05-15 20:35 UTC, evgenymarkov commented on blocks/card.css
> +.card__label[data-value^='5.']
🔥

2018-05-15 20:35 UTC, evgenymarkov commented on blocks/card.css
> +    color: darkgray;
hex

2018-05-15 20:35 UTC, evgenymarkov commented on blocks/form.css
> +    font-size: 22pt;
pt? Может rem для шрифтов всё таки сделать?

2018-05-15 20:35 UTC, evgenymarkov commented on blocks/hamburger.css
> +    padding: 15px;
Где-то px, где-то em. Приведёшь к общему знаменателю?

2018-05-15 20:35 UTC, evgenymarkov commented on blocks/form.css
> +    box-sizing: border-box;
Размер шрифта маловат для такого громадного инпута

2018-05-15 20:35 UTC, evgenymarkov commented on blocks/hamburger.css
> +    transition-property: transform;
И даже webstorm не ругался и не предлагал склеить в составное свойство?

2018-05-15 20:35 UTC, evgenymarkov commented on blocks/head.css
> +    font-size: 33pt;
rem или px

2018-05-15 20:35 UTC, evgenymarkov commented on blocks/head.css
> +    padding: 1rem 1.5rem 1rem 1em;
Приведи к какой-то одной единице

2018-05-15 20:35 UTC, evgenymarkov commented on blocks/page.css
> +    font-size: 10pt;
px или rem

2018-05-15 20:35 UTC, evgenymarkov commented on blocks/page.js
> +        const ACTIVATION_THRESHOLD = 200;
Можно обернуть код в IIFE и записать константы на уровне модуля

2018-05-15 20:35 UTC, evgenymarkov commented on index.html
> +    <button class="head__button">Найти</button>
`cursor: pointer` не хватает

2018-05-15 20:35 UTC, evgenymarkov commented on blocks/page.css
> +        display: block;
![2018-05-16_01-30-49](https://user-images.githubusercontent.com/16443248/40081922-df916660-58a8-11e8-9ba7-f1a30eb08aab.png)

2018-05-15 20:35 UTC, evgenymarkov commented on blocks/page.css
> +        display: block;
Есть условие, но в хромиуме скроллится
> При открытом меню содержимое страницы не скроллится

2018-05-16 13:21 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-05-16 18:11 UTC, evgenymarkov approved these changes
🍏

2018-05-16 18:11 UTC, closed without merging