xx
urfu-2017/webdev-task-4 pull request #9
Opened 2018-03-28 18:06 UTC by trszdev

2018-04-01 07:25 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-04-12 07:40 UTC, nex2hex requested changes
в целом все хорошо

2018-04-12 07:40 UTC, nex2hex commented on index.js
> +const ofClass = cls => document.querySelector(`.${cls}`);
`ofClass ` уж лучше тогда `findByClass` или просто `$`

2018-04-12 07:40 UTC, nex2hex commented on index.js
> +        if (e.keyCode === 13) {
13 надо вынести в константу

2018-04-12 07:40 UTC, nex2hex commented on index.js
> +onEnter(searchInput, async () => {
зачем тут async?

2018-04-12 07:40 UTC, nex2hex commented on index.js
> +    if (!searchInput.value) {
searchInput.value.trim() чтобы не реагировало на пробелы

2018-04-12 07:40 UTC, nex2hex commented on index.js
> +        if (e.keyCode === 13) {
13 в константу

2018-04-12 07:40 UTC, nex2hex commented on index.js
> +const ofClass = cls => document.querySelector(`.${cls}`);
`findByClass` или просто `$`

```
const $ = selector => document.querySelector(selector);
const searchButton = $('.header-searchbar-btn');
```

2018-04-12 07:40 UTC, nex2hex commented on index.js
> +onEnter(searchInput, async () => {
зачем async и промис тут?

```
const onEnter = (elem, callback) => {...}
onEnter(searchInput, searchButton.click);
```

2018-04-12 07:40 UTC, nex2hex commented on index.js
> +    if (!searchInput.value) {
searchInput.value.trim() чтобы не реагировать на пробелы

2018-04-15 17:56 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-04-16 08:01 UTC, nex2hex commented
🍏

2018-04-16 08:01 UTC, closed without merging